apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
spec:
  project: default
  # When you specify the sources field, Argo CD will ignore the source (singular) field.
  # source:
  #   path: charts
  #   repoURL: 'https://github.com/SahatasLee/ArgoCD.git'
  #   targetRevision: HEAD
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    chart: mysql
    targetRevision: 11.1.14
    helm:
      valueFiles:
      - $values/example/mysql/values.yaml
  - repoURL: 'https://github.com/SahatasLee/ArgoCD.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
